name: build-docker-image

on: 
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/buildImage.yml'

env: 
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # import the multi-stage docker build action
      - name: Multi-stage Docker Build
        uses: Firehed/multistage-docker-build-action@v1.5.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # use the multistage docker build action instead of docker's action
      - uses: firehed/multistage-docker-build-action@v1
        id: build
        with:
          context: .
          repository: ghcr.io/firehed/actions
          tag-latest-on-default: true
          stages: stage1, stage2, stage3
          testenv-stage: testenv
          server-stage: server
          build-args: |
            PY_VERSION=${{ matrix.python-version }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     build-args: |
      #       PY_VERSION=${{ matrix.python-version }}
      #     push: true 
      #     tags: ${{ env.REGISTRY }}/${{ github.repository }}/learn-maintenance-image-${{ matrix.python-version }}:latest
