name: release-test

on:
  workflow_dispatch:
  pull_request:
  push:
  release:

jobs:
  echo-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: See what github.ref_name is on release
        run: echo ${{ github.ref_name }}