# automatically runs pytest to test the length conversion program whenever code is pushed to github

name: test-conversion-program
on: push
jobs:
  run-test-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install numpy
      - run: pip install -U pytest coverage coveralls PyYAML
      - run: coverage run -m --source=. pytest
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: coverage report