# automatically runs pytest to test the length conversion program whenever code is pushed to github

name: test-conversion-program

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  run-test-code:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/learn-maintenance-image:latest${{ matrix.python-version }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: coverage run -m --source=. pytest
      - run: coverage lcov
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: coverage report